### ISSUE TITLE
Default status code from Err should be 500

### ISSUE THREAD

**Issue by joaommartins** [enzious/actix-web-thiserror#2]
When returning from an actix-web endpoint an Err(T) where T: impl ResponseError, the expected default error should be, in my opinion, 500 InternalServerError.

This should be a relatively simple fix by changing this line: https://github.com/enzious/actix-web-thiserror/blob/47ba43d42f87a4deba8d24b57361f6680ba9ca70/actix-web-thiserror-derive/src/response_error.rs#LL197C46-L197C46

**Comment by enzious** [comment]
I'll look into the changing the default, maybe providing a global config.

**Comment by enzious** [comment]
Addressed in #4
