### ISSUE TITLE
Reliance upon using dependencies.

### ISSUE THREAD

**Issue by Stefanuk12** [enzious/actix-web-thiserror#5]
In order to use the `ResponseError` derive macro, the user must use `actix_web::http`, `thiserror::Error`, `log::Error`. This is not ideal, and you should not do this.

Whenever possible, use a full import within your macro to avoid issues and having to use these dependencies.

For example, instead of `http::StatusCode`, use `actix_web::http::StatusCode`.

**Comment by jayvdb** [comment]
I've got two PRs up which resolve two of them.

I think it isnt possible to remove the need to import `thiserror::Error`, as this is needed anyway by the caller.

But I support the caller could do `use thiserror::Error as ThisError` , and that should still work.  I'll also investigate that.

**Comment by jayvdb** [comment]
> I suppose the caller could do use thiserror::Error as ThisError , and that should still work. I'll also investigate that.

I've tested this - no problems.
